/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class usb_macosx_MacOSX_HostImpl */

#ifndef _Included_usb_macosx_MacOSX_HostImpl
#define _Included_usb_macosx_MacOSX_HostImpl
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
