/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class usb_macosx_MacOSX */

#ifndef _Included_usb_macosx_MacOSX
#define _Included_usb_macosx_MacOSX
#ifdef __cplusplus
extern "C" {
#endif
#undef usb_macosx_MacOSX_trace
#define usb_macosx_MacOSX_trace 0L
#undef usb_macosx_MacOSX_debug
#define usb_macosx_MacOSX_debug 0L
/*
 * Class:     usb_macosx_MacOSX
 * Method:    scanForDevices
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_usb_macosx_MacOSX_scanForDevices
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     usb_macosx_MacOSX
 * Method:    haltDeviceScan
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_usb_macosx_MacOSX_haltDeviceScan
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
